# Generated by Django 4.1.2 on 2022-10-18 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0002_alter_departamentos_porcentaje'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamentos',
            options={'managed': True, 'ordering': ['id'], 'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
        migrations.AlterModelOptions(
            name='propietarios',
            options={'managed': True, 'ordering': ['apellido', 'nombre'], 'verbose_name': 'Propietario', 'verbose_name_plural': 'Propietarios'},
        ),
    ]
