# Generated by Django 4.1.2 on 2022-10-20 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0003_alter_departamentos_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('anio', models.IntegerField()),
                ('tipo_movimiento', models.CharField(max_length=1)),
                ('fecha_movimiento', models.DateField()),
                ('detalle', models.CharField(max_length=100)),
                ('importe', models.FloatField(default=0)),
                ('comprobante', models.CharField(blank=True, max_length=50, null=True)),
                ('expensas', models.CharField(choices=[('Corresponde', 'S'), ('No Corresponde', 'N')], max_length=14)),
            ],
            options={
                'verbose_name': 'Movimientos',
                'verbose_name_plural': 'Movimientos',
                'db_table': 'movimientos',
                'ordering': ['id'],
            },
        ),
    ]
